openapi: 3.0.3
info:
  title: Goat facts Service
  description: Service for obtaining your daily dose of goat facts
  version: "1.0"
servers:
- url: http://localhost:8080
- url: https://goatops.farm
paths:
  /facts:
    get:
      tags:
      - goatfacts
      summary: list-facts goatfacts
      operationId: goatfacts#list-facts
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fact'
                example:
                - id: 123abc
                  text: Goats will not rick-roll you
                - id: 123abc
                  text: Goats will not rick-roll you
                - id: 123abc
                  text: Goats will not rick-roll you
                - id: 123abc
                  text: Goats will not rick-roll you
              example:
              - id: 123abc
                text: Goats will not rick-roll you
              - id: 123abc
                text: Goats will not rick-roll you
  /facts/{id}:
    get:
      tags:
      - goatfacts
      summary: get-fact goatfacts
      operationId: goatfacts#get-fact
      parameters:
      - name: id
        in: path
        description: ID of the fact
        required: true
        schema:
          type: string
          description: ID of the fact
          example: Molestias molestiae accusantium quo adipisci illum.
        example: Dolorem dolore qui a voluptas.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fact'
              example:
                id: 123abc
                text: Goats will not rick-roll you
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /facts/random:
    get:
      tags:
      - goatfacts
      summary: get-random-fact goatfacts
      operationId: goatfacts#get-random-fact
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fact'
              example:
                id: 123abc
                text: Goats will not rick-roll you
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /openapi.json:
    get:
      tags:
      - goatfacts
      summary: Download ./gen/http/openapi3.json
      operationId: goatfacts#/openapi.json
      responses:
        "200":
          description: File downloaded
  /swagger.json:
    get:
      tags:
      - goatfacts
      summary: Download ./gen/http/openapi.json
      operationId: goatfacts#/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    Fact:
      type: object
      properties:
        id:
          type: string
          description: A unique ID
          example: 123abc
          minLength: 1
          maxLength: 255
        text:
          type: string
          description: Fact text
          example: Goats will not rick-roll you
      example:
        id: 123abc
        text: Goats will not rick-roll you
      required:
      - id
      - text
tags:
- name: goatfacts
  description: The goatfacts service provides you with important facts about goats.
