swagger: "2.0"
info:
  title: Goat facts Service
  description: Service for obtaining your daily dose of goat facts
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /facts:
    get:
      tags:
      - goatfacts
      summary: list-facts goatfacts
      operationId: goatfacts#list-facts
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/FactResponse'
      schemes:
      - http
  /facts/{id}:
    get:
      tags:
      - goatfacts
      summary: get-fact goatfacts
      operationId: goatfacts#get-fact
      parameters:
      - name: id
        in: path
        description: ID of the fact
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GoatfactsGetFactResponseBody'
            required:
            - id
            - text
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/GoatfactsGetFactBadRequestResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/GoatfactsGetFactNotFoundResponseBody'
      schemes:
      - http
  /facts/random:
    get:
      tags:
      - goatfacts
      summary: get-random-fact goatfacts
      operationId: goatfacts#get-random-fact
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GoatfactsGetRandomFactResponseBody'
            required:
            - id
            - text
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/GoatfactsGetRandomFactNotFoundResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - goatfacts
      summary: Download ./gen/http/openapi.json
      operationId: goatfacts#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
  /openapi.yaml:
    get:
      tags:
      - goatfacts
      summary: Download ./gen/http/openapi.yaml
      operationId: goatfacts#/openapi.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
definitions:
  FactResponse:
    title: FactResponse
    type: object
    properties:
      id:
        type: string
        description: A unique ID
        example: 123abc
        minLength: 1
        maxLength: 255
      text:
        type: string
        description: Fact text
        example: Goats will not rick-roll you
    description: A fact about goats.
    example:
      id: 123abc
      text: Goats will not rick-roll you
    required:
    - id
    - text
  GoatfactsGetFactBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: get-fact_BadRequest_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GoatfactsGetFactNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: get-fact_NotFound_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GoatfactsGetFactResponseBody:
    title: GoatfactsGetFactResponseBody
    type: object
    properties:
      id:
        type: string
        description: A unique ID
        example: 123abc
        minLength: 1
        maxLength: 255
      text:
        type: string
        description: Fact text
        example: Goats will not rick-roll you
    example:
      id: 123abc
      text: Goats will not rick-roll you
    required:
    - id
    - text
  GoatfactsGetRandomFactNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: get-random-fact_NotFound_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GoatfactsGetRandomFactResponseBody:
    title: GoatfactsGetRandomFactResponseBody
    type: object
    properties:
      id:
        type: string
        description: A unique ID
        example: 123abc
        minLength: 1
        maxLength: 255
      text:
        type: string
        description: Fact text
        example: Goats will not rick-roll you
    example:
      id: 123abc
      text: Goats will not rick-roll you
    required:
    - id
    - text
